import { type IOptions } from "sanitize-html";
import checkIframe from "./checkIframe.js";
import checkScript from "./checkScript.js";

export const SANITIZE_HTML_OPTIONS: IOptions = {
  allowedAttributes: {
    "*": [
      "id",
      "href",
      "title",
      "class",
      "style",
      "data-lang",
      "lang",
      "align",
      "dir",
    ],
    a: ["name", "target"],
    font: ["size", "color"],
    form: ["action"],
    iframe: [
      "src",
      "frameborder",
      "name",
      "height",
      "width",
      "border",
      "cellspacing",
      "scrolling",
      "allow",
      "allowfullscreen",
      "webkitallowfullscreen",
      "mozallowfullscreen",
    ],
    img: ["src", "alt", "width", "height", "caption", "cite"],
    input: ["type", "name", "value", "checked"],
    script: ["src", "type", "async", "charset"],
    ol: ["start"],
    table: ["border", "cellpadding", "cellspacing"],
    tt: ["weight"],
    math: ["display", "xmlns"],
    menclose: ["notation"],
    mfenced: ["open", "close", "separators", "mrow"],
    mfrac: ["linethickness", "numalign", "denomalign", "bevelled"],
    mi: ["mathvariant"],
    mn: ["mathvariant"],
    mo: [
      "fence",
      "separator",
      "lspace",
      "rspace",
      "stretchy",
      "symmetric",
      "mathvariant",
    ],
    mpadded: ["width", "height", "depth", "lspace", "voffset"],
    mrow: ["dir", "mathbackground", "mathcolor"],
    ms: ["lquote", "rquote"],
    mspace: ["width", "height", "depth"],
    mstyle: [
      "displaystyle",
      "scriptlevel",
      "mathcolor",
      "mathbackground",
      "mathsize",
      "fontfamily",
      "fontweight",
      "fontstyle",
    ],
    mtable: [
      "align",
      "columnalign",
      "rowalign",
      "columnspacing",
      "rowspacing",
      "width",
      "frame",
      "framespacing",
      "equalcolumns",
      "equalrows",
    ],
    mtd: [
      "columnalign",
      "rowalign",
      "columnspan",
      "rowspan",
      "width",
      "height",
      "depth",
    ],
    mtr: ["rowalign"],
    munder: ["accentunder"],
    munderover: ["accent", "accentunder"],
  },
  disallowedTagsMode: "escape",
  parser: {
    decodeEntities: false,
  },
  allowedTags: [
    "a",
    "center",
    "address",
    "article",
    "aside",
    "footer",
    "font",
    "form",
    "header",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hgroup",
    "main",
    "nav",
    "section",
    "script",
    "blockquote",
    "dd",
    "details",
    "div",
    "dl",
    "dt",
    "figcaption",
    "figure",
    "hr",
    "li",
    "math",
    "menclose",
    "merror",
    "mfenced",
    "mfrac",
    "mi",
    "mn",
    "mo",
    "mmultiscripts",
    "mpadded",
    "mphantom",
    "mroot",
    "mrow",
    "ms",
    "mspace",
    "msqrt",
    "mstyle",
    "msub",
    "msup",
    "msubsup",
    "mtable",
    "mtd",
    "mtext",
    "mtr",
    "munder",
    "munderover",
    "semantics",
    "ol",
    "p",
    "pre",
    "ul",
    "a",
    "abbr",
    "b",
    "bdi",
    "bdo",
    "br",
    "cite",
    "code",
    "data",
    "dfn",
    "em",
    "i",
    "input",
    "iframe",
    "kbd",
    "mark",
    "q",
    "rb",
    "rp",
    "rt",
    "rtc",
    "ruby",
    "s",
    "samp",
    "small",
    "span",
    "strike",
    "strong",
    "sub",
    "summary",
    "sup",
    "time",
    "u",
    "var",
    "wbr",
    "caption",
    "col",
    "colgroup",
    "table",
    "tbody",
    "td",
    "tfoot",
    "th",
    "thead",
    "tr",
    "tt",
    "img",
  ],
  transformTags: {
    iframe: checkIframe,
    script: checkScript,
  },
  allowVulnerableTags: true,
};
